import { normalizeExpression } from "./expression-input";
import { parse, derivative, simplify, type MathNode, type OperatorNode, type FunctionNode, type ParenthesisNode } from 'mathjs';
import type { Inputs, Result, ExplanationStep } from './math-engine';
const raw=String.raw;
const f=(n:number)=>Number(n.toPrecision(10)).toString();
const tex=(source:string)=>{try{return parse(source).toTex({parenthesis:'auto',implicit:'hide'});}catch{return raw`\text{${source.replace(/[{}\\]/g,'')}}`;}};
const t=(n:number)=>tex(f(n));
const step=(title:string,explanation:string,latex?:string,check?:string):ExplanationStep=>({title,explanation,latex,check});
const unwrap=(n:MathNode):MathNode=>n.type==='ParenthesisNode'?unwrap((n as ParenthesisNode).content):n;
const matrixTex=(a:number[][])=>raw`\begin{pmatrix}${a.map(row=>row.map(t).join('&')).join(raw`\\`)}\end{pmatrix}`;
const vector=(s:string)=>s.split(',').map(Number);
function derivativeWalk(input:MathNode,steps:ExplanationStep[]){
 const node=unwrap(input),latex=node.toTex({parenthesis:'auto'});
 if(node.type==='ConstantNode'||(node.type==='SymbolNode'&&node.toString()!=='x')){steps.push(step('Una constante no cambia','Este término no depende de x. Si x varía, su valor permanece igual; por eso su tasa de cambio es cero.',raw`\frac{d}{dx}\left(${latex}\right)=0`));return;}
 if(node.type==='SymbolNode'){steps.push(step('Derivar la variable','La función x aumenta una unidad por cada unidad que aumenta x. Su pendiente es 1.',raw`\frac{d}{dx}(x)=1`));return;}
 if(node.type==='OperatorNode'){
  const op=node as OperatorNode,u=op.args[0],v=op.op==='*'&&op.args.length>2?parse(op.args.slice(1).map(a=>`(${a.toString()})`).join('*')):op.args[1];
  if(['+','-'].includes(op.op)){steps.push(step('Separar los términos','La derivada es lineal: podemos derivar cada término por separado y conservar el signo que lo une al resto.',raw`\frac{d}{dx}\left(${latex}\right)`));op.args.forEach(arg=>derivativeWalk(arg,steps));}
  else if(op.op==='*'||op.op==='/'){
   const rule=op.op==='*'?raw`(uv)'=u'v+uv'`:raw`\left(\frac uv\right)'=\frac{u'v-uv'}{v^2}`;
   steps.push(step(op.op==='*'?'Identificar un producto':'Identificar un cociente',op.op==='*'?'No multiplicamos las derivadas. Derivamos el primer factor dejando el segundo, y después el segundo dejando el primero. Sumamos ambos aportes.':'Derivamos el numerador y multiplicamos por el denominador; restamos numerador por derivada del denominador, y dividimos entre el denominador al cuadrado. El denominador original no puede ser cero.',rule));
   steps.push(step('Nombrar las partes','Estas letras son auxiliares: permiten ver con claridad qué función ocupa cada lugar en la regla.',raw`u=${u.toTex()},\qquad v=${v.toTex()}`));derivativeWalk(u,steps);derivativeWalk(v,steps);
   const du=derivative(u,'x').toTex(),dv=derivative(v,'x').toTex();steps.push(step('Sustituir en la regla','Coloca cada derivada en su posición sin perder los factores que se mantienen. Los paréntesis conservan el orden de las operaciones.',op.op==='*'?raw`\left(${du}\right)\left(${v.toTex()}\right)+\left(${u.toTex()}\right)\left(${dv}\right)`:raw`\frac{\left(${du}\right)\left(${v.toTex()}\right)-\left(${u.toTex()}\right)\left(${dv}\right)}{\left(${v.toTex()}\right)^2}`));
  }else if(op.op==='^'){
   const dv=derivative(v,'x');
   if(dv.toString()==='0'){steps.push(step('Aplicar potencia y cadena','El exponente baja multiplicando y se reduce en una unidad. Si la base contiene otra función, también multiplicamos por la derivada de esa base.',raw`\frac{d}{dx}u^n=n\,u^{n-1}\,u',\qquad u=${u.toTex()},\quad n=${v.toTex()}`));derivativeWalk(u,steps);}
   else{steps.push(step('Base y exponente requieren atención','Cuando el exponente depende de x, usamos derivación logarítmica. Esta forma real se interpreta donde la base es positiva; revisa además el dominio original.',raw`\frac{d}{dx}u^v=u^v\left(v'\ln u+v\frac{u'}u\right)`));derivativeWalk(u,steps);derivativeWalk(v,steps);}
  }
 }else if(node.type==='FunctionNode'){
  const fn=node as FunctionNode,u=fn.args[0],name=fn.fn.toString();
  const rules:Record<string,string>={sec:raw`(\sec u)'=\sec(u)\tan(u)u'`,csc:raw`(\csc u)'=-\csc(u)\cot(u)u'`,cot:raw`(\cot u)'=-\csc^2(u)u'`,sin:raw`(\sin u)'=\cos(u)u'`,cos:raw`(\cos u)'=-\sin(u)u'`,tan:raw`(\tan u)'=\frac{u'}{\cos^2 u}`,exp:raw`(e^u)'=e^u u'`,log:raw`(\ln u)'=\frac{u'}u`,sqrt:raw`(\sqrt u)'=\frac{u'}{2\sqrt u}`,abs:raw`(|u|)'=\operatorname{sign}(u)u'\quad(u\ne0)`};
  steps.push(step('Reconocer una función compuesta',`La función exterior es ${name} y su argumento es la función interior. Usamos la regla de la cadena: derivada exterior evaluada en el interior, multiplicada por la derivada interior.`,rules[name]));steps.push(step('Identificar la función interior','Nombramos u al argumento completo, no solo a la variable x.',raw`u(x)=${u.toTex()}`));derivativeWalk(u,steps);
 }
 steps.push(step('Reunir y simplificar este término','Sustituimos las derivadas calculadas y agrupamos factores y términos compatibles. Simplificar cambia la escritura, no la función en su dominio.',raw`\frac{d}{dx}\left(${latex}\right)=${derivative(node,'x').toTex()}`));
}
function integralWalk(input:MathNode,steps:ExplanationStep[]):string {
 const node=unwrap(input),source=node.toString();
 let depends=false;node.traverse(n=>{if(n.type==='SymbolNode'&&n.toString()==='x')depends=true;});
 if(!depends){const value=node.evaluate() as number;steps.push(step('Integrar una constante','Buscamos una función cuya derivada sea esta constante. Multiplicarla por x produce exactamente esa derivada.',raw`\int ${t(value)}\,dx=${t(value)}x`));return `(${value})*x`;}
 if(source==='x'){steps.push(step('Reconocer una potencia de exponente uno','x es x¹. Sumamos uno al exponente y dividimos entre el nuevo exponente, porque al derivar se recuperará el factor original.',raw`\int x\,dx=\int x^1\,dx=\frac{x^{1+1}}{1+1}=\frac{x^2}{2}`));return'x^2/2';}
 if(node.type==='OperatorNode'){
  const op=node as OperatorNode,[a,b]=op.args;
  if(['+','-'].includes(op.op)){steps.push(step('Usar la linealidad de la integral','Separamos la suma o resta en integrales más pequeñas. Cada signo permanece asociado a su término; al final sumaremos una sola constante de integración.',raw`\int\left(${node.toTex()}\right)dx`));const parts=op.args.map(n=>integralWalk(n,steps));return parts.length===1?`${op.op}(${parts[0]})`:`(${parts[0]})${op.op}(${parts[1]})`;}
  if(op.op==='*'){
   let ca:number|null=null,cb:number|null=null;try{ca=a.evaluate();}catch{}try{cb=b.evaluate();}catch{}
   const value=typeof ca==='number'?ca:cb,other=typeof ca==='number'?b:a;
   steps.push(step('Sacar el factor constante','Un factor que no depende de x puede colocarse fuera de la integral. Lo conservamos para multiplicar la primitiva obtenida.',raw`\int ${node.toTex()}\,dx=${t(Number(value))}\int ${other.toTex()}\,dx`));return `(${value})*(${integralWalk(other,steps)})`;
  }
  if(op.op==='/'){
   let denominator:number|null=null;try{denominator=b.evaluate();}catch{}
   if(typeof denominator==='number'){steps.push(step('Dividir por una constante','Dividir todo el integrando por una constante equivale a multiplicar la integral por su inversa.',raw`\int\frac{${a.toTex()}}{${b.toTex()}}dx=\frac{1}{${b.toTex()}}\int ${a.toTex()}dx`));return`(${integralWalk(a,steps)})/(${denominator})`;}
   const numerator=a.evaluate();steps.push(step('Reconocer la excepción logarítmica','La regla de potencia no permite dividir entre cero cuando el exponente es −1. En su lugar usamos ln|x|, cuya derivada es 1/x para x distinto de cero.',raw`\int\frac{${t(numerator)}}x\,dx=${t(numerator)}\ln|x|`));return`(${numerator})*log(abs(x))`;
  }
  if(op.op==='^'){
   const power=b.evaluate() as number;
   if(power===-1){steps.push(step('Tratar el exponente −1','Esta es la excepción a la regla de potencia: su primitiva es logarítmica y se define por separado a cada lado de cero.',raw`\int x^{-1}\,dx=\ln|x|`));return'log(abs(x))';}
   steps.push(step('Aplicar la regla de potencia','Sumamos 1 al exponente y dividimos por ese nuevo exponente. Esto compensa el factor que aparecería al derivar la primitiva.',raw`\int x^{${t(power)}}dx=\frac{x^{${t(power)}+1}}{${t(power)}+1}=\frac{x^{${t(power+1)}}}{${t(power+1)}}`));return`x^(${power+1})/(${power+1})`;
  }
 }
 if(node.type==='FunctionNode'){
  const fn=node as FunctionNode,name=fn.fn.toString(),arg=fn.args[0];
  if(name==='sqrt'){steps.push(step('Reescribir la raíz como potencia','La raíz cuadrada es una potencia de exponente 1/2. Integramos sumando uno a ese exponente y dividiendo entre 3/2.',raw`\int\sqrt{x}\,dx=\int x^{1/2}dx=\frac{x^{3/2}}{3/2}=\frac23x^{3/2}`));return'2*x^1.5/3';}
  const slope=derivative(arg,'x').evaluate() as number;
  steps.push(step('Hacer una sustitución lineal','El argumento de la función es una expresión lineal. Lo llamamos u; su derivada es constante, así que dx puede expresarse como du dividido entre esa constante.',raw`u=${arg.toTex()},\qquad du=${t(slope)}dx,\qquad dx=\frac{du}{${t(slope)}}`));
  const forms:Record<string,string>={sin:raw`\int\sin u\,du=-\cos u`,cos:raw`\int\cos u\,du=\sin u`,exp:raw`\int e^u\,du=e^u`};
  steps.push(step('Integrar en la nueva variable','Usamos la primitiva conocida de la función exterior y conservamos el factor de la sustitución.',forms[name]));
  const answer=`${name==='sin'?'-cos':name==='cos'?'sin':'exp'}(${arg.toString()})/(${slope})`;
  steps.push(step('Volver a la variable original','Reemplazamos u por su expresión en x. No dejamos la respuesta en la variable auxiliar.',raw`\int ${node.toTex()}dx=${tex(answer)}`));return answer;
 }
 return source;
}
function rowReduction(a:number[][],right:number[][],steps:ExplanationStep[]):number[][]{
 const size=a.length,rows=a.map((row,i)=>[...row,...right[i]]);
 steps.push(step('Construir la matriz ampliada','Cada fila representa una ecuación. A la izquierda están los coeficientes; a la derecha, los valores que debemos transformar mediante las mismas operaciones.',matrixTex(rows)));
 for(let col=0;col<size;col++){
  let pivot=col;for(let i=col+1;i<size;i++)if(Math.abs(rows[i][col])>Math.abs(rows[pivot][col]))pivot=i;
  if(rows[pivot][col]===0)throw new Error('No se puede desarrollar la eliminación con un pivote nulo.');
  if(pivot!==col){[rows[pivot],rows[col]]=[rows[col],rows[pivot]];steps.push(step('Elegir un pivote estable',`Intercambiamos las filas ${col+1} y ${pivot+1} para usar un coeficiente de mayor magnitud como pivote. Cambiar el orden de las ecuaciones no cambia su solución.`,raw`F_{${col+1}}\leftrightarrow F_{${pivot+1}},\qquad ${matrixTex(rows)}`));}
  const divisor=rows[col][col];rows[col]=rows[col].map(x=>x/divisor);
  steps.push(step('Convertir el pivote en uno',`Dividimos todos los elementos de la fila ${col+1} entre ${f(divisor)}. Hacer la misma división a ambos lados conserva la igualdad.`,raw`F_{${col+1}}\leftarrow\frac{F_{${col+1}}}{${t(divisor)}},\qquad ${matrixTex(rows)}`));
  for(let row=0;row<size;row++)if(row!==col&&rows[row][col]!==0){const factor=rows[row][col];rows[row]=rows[row].map((x,j)=>x-factor*rows[col][j]);steps.push(step('Eliminar la incógnita en otra fila',`Restamos ${f(factor)} veces la fila ${col+1} a la fila ${row+1}. Así se hace cero el coeficiente de esta columna sin alterar el conjunto de soluciones.`,raw`F_{${row+1}}\leftarrow F_{${row+1}}-(${t(factor)})F_{${col+1}},\qquad ${matrixTex(rows)}`));}
 }
 return rows;
}
export function explainResult(slug:string,v:Inputs,r:Result):Result{
 const n=(key:string)=>Number(v[key]);let steps:ExplanationStep[]=[];
 const add=(title:string,explanation:string,latex?:string,check?:string)=>steps.push(step(title,explanation,latex,check));
 if(['ecuaciones-lineales','ecuaciones-cuadraticas','ecuaciones-cubicas'].includes(slug)){
  const requested=slug==='ecuaciones-lineales'?1:slug==='ecuaciones-cuadraticas'?2:3;
  const coefficients=['a','b','c','d'].slice(0,requested+1).map(n);while(coefficients.length>1&&coefficients[0]===0)coefficients.shift();const degree=coefficients.length-1;
  const poly=coefficients.map((c,i)=>`(${c})*x^${degree-i}`).join('+');
  add('Leer la ecuación y ordenar los términos','Queremos encontrar los valores de x que hacen que el lado izquierdo valga cero. Primero identificamos el grado real del polinomio y sus coeficientes.',raw`${tex(poly)}=0`);
  if(degree<requested)add('Revisar el grado efectivo','El coeficiente principal introducido es cero. Ese término desaparece, así que utilizamos el método del grado que realmente queda.',raw`\text{Grado efectivo: }${degree}`);
  if(degree===0){add('Comprobar una igualdad constante',coefficients[0]===0?'Queda 0 = 0: la igualdad no depende de x y siempre se cumple. Todos los valores de x son soluciones.':'Queda una constante distinta de cero igualada a cero. Ningún valor de x puede convertir esa igualdad en verdadera.',raw`${t(coefficients[0])}=0`);r.latex=coefficients[0]===0?raw`x\in\mathbb R`:raw`S=\varnothing`;}
  if(degree===1){const[a,b]=coefficients,root=-b/a;
   add('Eliminar el término independiente',`Restamos ${f(b)} a ambos lados. No «cambiamos un signo» sin más: hacemos la misma operación en ambos miembros para conservar la igualdad.`,raw`${t(a)}x+(${t(b)})-(${t(b)})=0-(${t(b)})`);
   add('Simplificar ambos miembros','En el lado izquierdo, el término independiente y su opuesto se cancelan. Solo queda el producto del coeficiente por x.',raw`${t(a)}x=${t(-b)}`);
   add('Despejar la incógnita',`Dividimos ambos miembros entre ${f(a)}, que es distinto de cero. El coeficiente de x se convierte en 1.`,raw`\frac{${t(a)}x}{${t(a)}}=\frac{${t(-b)}}{${t(a)}}\quad\Longrightarrow\quad x=${t(root)}`);
   add('Comprobar sustituyendo','Volvemos a la ecuación original y sustituimos x por el valor encontrado. Si el resultado es cero, la solución cumple la condición inicial.',raw`${t(a)}\left(${t(root)}\right)+(${t(b)})\approx 0`,'La comprobación numérica puede incluir redondeo.');r.latex=raw`x=${t(root)}`;
  }
  if(degree===2){const[a,b,c]=coefficients,delta=b*b-4*a*c;
   add('Identificar los coeficientes','Compara tu ecuación con ax² + bx + c = 0. El signo forma parte de cada coeficiente; un término ausente tiene coeficiente cero.',raw`a=${t(a)},\quad b=${t(b)},\quad c=${t(c)}`);
   add('Escribir la fórmula general','La fórmula general resuelve cualquier cuadrática con a distinto de cero. El símbolo ± indica que calcularemos dos ramas.',raw`x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}`);
   add('Calcular primero el discriminante','Para evitar errores, calculamos por separado b² y 4ac, y luego los restamos. El resultado determina el tipo de raíces.',raw`\Delta=(${t(b)})^2-4(${t(a)})(${t(c)})=${t(b*b)}-(${t(4*a*c)})=${t(delta)}`);
   add('Interpretar el discriminante',delta>0?'La raíz cuadrada del discriminante es real y no nula. Las ramas positiva y negativa producen dos soluciones reales diferentes.':delta===0?'La raíz del discriminante es cero. Las dos ramas coinciden: hay una única raíz distinta, de multiplicidad dos.':'La raíz de un número negativo no es real. Trabajamos con i, donde i² = −1, y obtenemos dos soluciones complejas conjugadas.',raw`\Delta ${delta>0?'>':delta===0?'=':'<'}0`);
   add('Sustituir sin perder signos','Coloca los coeficientes y el discriminante calculado en la fórmula. Conserva paréntesis alrededor de los números negativos.',raw`x=\frac{-(${t(b)})\pm\sqrt{${t(delta)}}}{2(${t(a)})}`);
   if(delta>=0){const root=Math.sqrt(delta),q=-0.5*(b+(b>=0?root:-root)),x1=delta===0?-b/(2*a):b>=0?c/q:q/a,x2=delta===0?x1:b>=0?q/a:c/q;add('Resolver la rama positiva','En esta rama tomamos el signo + antes de la raíz. Calculamos el numerador completo y después dividimos entre el denominador.',raw`x_1=\frac{${t(-b)}+${t(root)}}{${t(2*a)}}=${t(x1)}`);if(delta>0)add('Resolver la rama negativa','Ahora usamos el signo −. El denominador es el mismo; solo cambia el signo delante de la raíz.',raw`x_2=\frac{${t(-b)}-${t(root)}}{${t(2*a)}}=${t(x2)}`);r.latex=delta===0?raw`x=${t(x1)}\quad\text{(raíz doble)}`:raw`x_1=${t(x1)},\qquad x_2=${t(x2)}`;for(const root of [...new Set([x1,x2])])add('Verificar en la ecuación original',`Sustituye x por ${f(root)}. Usamos el polinomio original, no una ecuación intermedia, para comprobar el resultado.`,raw`${t(a)}(${t(root)})^2+(${t(b)})(${t(root)})+(${t(c)})\approx0`);}
   else{const real=-b/(2*a),imag=Math.abs(Math.sqrt(-delta)/(2*a));add('Extraer la unidad imaginaria','Usamos √(−m) = i√m para m positivo. Separamos la parte real y la parte imaginaria.',raw`\sqrt{${t(delta)}}=i\sqrt{${t(-delta)}},\qquad x=${t(real)}\pm ${t(imag)}i`);add('Comprobar las dos soluciones','Al sustituir cualquiera de las dos raíces, los términos imaginarios se cancelan y usamos i² = −1. Una comprobación equivalente es que su suma sea −b/a y su producto c/a.',raw`x_1+x_2=${t(-b/a)},\qquad x_1x_2=${t(c/a)}`);r.latex=raw`x_1=${t(real)}+${t(imag)}i,\qquad x_2=${t(real)}-${t(imag)}i`;}
  }
  if(degree===3){const[a,b,c,d]=coefficients,A=b/a,B=c/a,C=d/a,p=B-A*A/3,q=2*A**3/27-A*B/3+C,D=(q/2)**2+(p/3)**3;
   add('Normalizar el coeficiente principal',`Dividimos todos los términos entre ${f(a)} para que el coeficiente de x³ sea 1. La ecuación sigue teniendo las mismas raíces porque dividimos entre un número no nulo.`,raw`x^3+(${t(A)})x^2+(${t(B)})x+(${t(C)})=0`);
   add('Eliminar el término cuadrático','Usamos una nueva variable t. Esta traslación del eje horizontal está elegida para cancelar el término de grado dos al expandir.',raw`x=t-\frac{A}{3}=t-(${t(A/3)})`);
   add('Calcular el coeficiente p','Tras expandir y reunir términos, el coeficiente lineal de la cúbica reducida es B − A²/3.',raw`p=B-\frac{A^2}{3}=(${t(B)})-\frac{(${t(A)})^2}{3}=${t(p)}`);
   add('Calcular el término q','El término independiente reúne las contribuciones de la sustitución al cubo, al término lineal y al término constante original.',raw`q=\frac{2A^3}{27}-\frac{AB}{3}+C=${t(q)}`);
   add('Escribir la cúbica reducida','Ahora solo aparecen un cubo, un término lineal y una constante. Esa forma permite aplicar Cardano o una parametrización trigonométrica.',raw`t^3+(${t(p)})t+(${t(q)})=0`);
   add('Decidir qué fórmula usar','Calculamos D = (q/2)² + (p/3)³. Aquí D es el discriminante de Cardano: su convención de signo no es la del discriminante polinómico.',raw`D=\left(\frac{${t(q)}}2\right)^2+\left(\frac{${t(p)}}3\right)^3=${t(D)}`);
   const tolerance=64*Number.EPSILON*(Math.abs((q/2)**2)+Math.abs((p/3)**3));
   if(D>tolerance){const u=Math.cbrt(-q/2+Math.sqrt(D)),w=Math.cbrt(-q/2-Math.sqrt(D));add('Calcular las dos raíces cúbicas auxiliares','D es positivo: existe una raíz real y un par complejo conjugado. Calculamos u y v usando raíces cúbicas reales, incluso si el radicando es negativo.',raw`u=\sqrt[3]{-q/2+\sqrt D}=${t(u)},\quad v=\sqrt[3]{-q/2-\sqrt D}=${t(w)}`);add('Recuperar las tres raíces de t','La suma u+v da la raíz real. Las otras dos raíces incorporan las raíces cúbicas de la unidad y forman un par conjugado.',raw`t_1=u+v,\quad t_{2,3}=-\frac{u+v}{2}\pm\frac{\sqrt3}{2}(u-v)i`);}
   else if(D < -tolerance){const arg=Math.max(-1,Math.min(1,(3*q/(2*p))*Math.sqrt(-3/p))),theta=Math.acos(arg)/3;add('Usar la forma trigonométrica','D es negativo, así que hay tres raíces reales. La identidad del ángulo triple permite obtenerlas sin operar con raíces cuadradas complejas intermedias.',raw`\theta=\frac13\arccos\left(\frac{3q}{2p}\sqrt{\frac{-3}{p}}\right)=${t(theta)}`);for(let k=0;k<3;k++)add(`Calcular la raíz real ${k+1}`,'Cambiamos k para recorrer las tres soluciones del ángulo triple. Los ángulos están expresados en radianes.',raw`t_{${k+1}}=2\sqrt{\frac{-p}{3}}\cos\left(\theta-\frac{2\pi(${k})}{3}\right)=${t(2*Math.sqrt(-p/3)*Math.cos(theta-2*Math.PI*k/3))}`);}
   else{const u=Math.cbrt(-q/2);add('Tratar las raíces repetidas','D es cero o numéricamente muy cercano a cero. La cúbica reducida tiene una raíz repetida; si p y q también son cero, la raíz t = 0 es triple.',raw`u=\sqrt[3]{-q/2}=${t(u)},\quad t_1=2u,\quad t_{2,3}=-u`);}
   add('Deshacer la sustitución','Las raíces calculadas corresponden a t. Restamos A/3 a cada una para volver a los valores de x de la ecuación original.',raw`x_k=t_k-(${t(A/3)})`);
   add('Verificar el conjunto de raíces','Puedes sustituir las raíces en el polinomio original. Las identidades de Viète ofrecen una segunda comprobación de su suma y producto, contando multiplicidades.',raw`x_1+x_2+x_3=-\frac ba=${t(-b/a)},\qquad x_1x_2x_3=-\frac da=${t(-d/a)}`);
   r.latex=r.answer.split('   ·   ').map(part=>part.replace(/x(\d+)/g,'x_{$1}')).join(raw`\qquad `);
  }
 }else if(slug==='derivadas'){
  let node=parse(normalizeExpression(v.expression));
  add('Interpretar lo que buscamos','Una derivada describe cómo cambia la función cuando cambia x. Antes de operar, identificamos la variable y la función completa.',raw`f(x)=${node.toTex()},\qquad \text{variable: }x`);
  for(let order=1;order<=n('order');order++){add(`Comenzar la derivada de orden ${order}`,order===1?'Reconocemos las operaciones que forman la función y aplicamos una regla a cada parte.':'Derivamos el resultado del orden anterior, no la función original de nuevo.',raw`\frac{d}{dx}\left(${node.toTex()}\right)`);derivativeWalk(node,steps);const expanded=derivative(node,'x',{simplify:false});node=derivative(node,'x');add('Ver la sustitución antes de simplificar','Esta expresión conserva factores como derivadas de x y constantes. Permite seguir de dónde provienen los términos antes de reducirlos.',expanded.toTex());add(`Resultado del orden ${order}`,'Reducimos multiplicaciones por uno, términos nulos y factores semejantes. No extendemos el dominio solo porque la expresión final parezca más sencilla.',raw`f^{(${order})}(x)=${node.toTex()}`);}
  r.latex=raw`f^{(${n('order')})}(x)=${node.toTex()}`;
  add('Interpretar y revisar el dominio','La primera derivada da pendientes; la segunda describe cómo cambia la pendiente. Revisa divisiones por cero, raíces y logaritmos tanto en la función original como en el resultado. La gráfica ayuda a explorar, pero no sustituye esa revisión.');
 }else if(slug==='integrales'){
  const node=parse(normalizeExpression(v.expression));
  add('Plantear la operación inversa','Buscamos una función F cuya derivada sea el integrando. Primero calculamos una primitiva y luego, si hay límites, la evaluamos en los extremos.',raw`F'(x)=${node.toTex()}`);
  const primitive=integralWalk(node,steps),F=simplify(primitive);
  add('Reunir las primitivas','Combinamos las partes con sus signos y factores. Todas las constantes independientes pueden reunirse en una sola constante C.',raw`F(x)=${F.toTex()}`);
  if(v.mode==='Definida'){
   const a=n('lower'),b=n('upper'),fa=Number(F.evaluate({x:a})),fb=Number(F.evaluate({x:b}));
   add('Revisar el intervalo','Antes de usar el teorema fundamental, comprobamos las restricciones de la familia admitida. No se permite atravesar una singularidad ni salir del dominio real.',raw`a=${t(a)},\qquad b=${t(b)}`);
   add('Aplicar el teorema fundamental','La integral definida se obtiene restando el valor de la primitiva en el extremo inferior al valor en el superior. La constante C se cancela.',raw`\int_{${t(a)}}^{${t(b)}}${node.toTex()}dx=F(${t(b)})-F(${t(a)})`);
   add('Evaluar el extremo superior',`Sustituimos x por ${f(b)} en toda la primitiva, respetando potencias y paréntesis.`,raw`F(${t(b)})=${t(fb)}`);
   add('Evaluar el extremo inferior',`Ahora sustituimos x por ${f(a)}. Incluso si este extremo es cero, hay que evaluar la expresión completa.`,raw`F(${t(a)})=${t(fa)}`);
   add('Restar e interpretar','Restamos en el orden superior menos inferior. El resultado mide acumulación con signo: las regiones bajo el eje aportan valores negativos, y al invertir los límites cambia el signo.',raw`${t(fb)}-(${t(fa)})=${t(fb-fa)}`);r.latex=raw`\int_{${t(a)}}^{${t(b)}}${node.toTex()}dx=${t(fb-fa)}`;
  }else{add('Añadir la constante de integración','La derivada de cualquier constante es cero. Por eso hay una familia de primitivas, todas separadas por una constante C.',raw`\int ${node.toTex()}dx=${F.toTex()}+C`);r.latex=raw`${F.toTex()}+C`;}
  add('Comprobar derivando','Una forma de revisar una primitiva es derivarla: las reglas de potencia y cadena deben devolver el integrando original en cada intervalo de su dominio.',raw`\frac{d}{dx}\left(F(x)+C\right)=${node.toTex()}`);
 }else if(slug==='sistemas-lineales'||slug==='matrices'){
  const a=v.matrix.split(';').map(vector),size=a.length,detValue=slug==='matrices'?Number(r.answer.split('=')[1]):undefined;
  add('Identificar la matriz y su tamaño',`Trabajamos con una matriz de ${size} filas y ${size} columnas. Las operaciones se aplican a filas completas, no a elementos aislados.`,raw`A=${matrixTex(a)}`);
  if(slug==='matrices'){
   if(size===2)add('Calcular el determinante',`Multiplicamos la diagonal principal y restamos el producto de la diagonal secundaria. El orden de la resta es importante.`,raw`\det(A)=(${t(a[0][0])})(${t(a[1][1])})-(${t(a[0][1])})(${t(a[1][0])})=${t(detValue!)}`);
   else{const positive=a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1]),middle=-a[0][1]*(a[1][0]*a[2][2]-a[1][2]*a[2][0]),last=a[0][2]*(a[1][0]*a[2][1]-a[1][1]*a[2][0]);add('Expandir por la primera fila','Calculamos tres menores 2×2. Los signos de los cofactores son +, −, +; multiplicamos cada menor por su elemento de la primera fila.',raw`\det A=a_{11}(a_{22}a_{33}-a_{23}a_{32})-a_{12}(a_{21}a_{33}-a_{23}a_{31})+a_{13}(a_{21}a_{32}-a_{22}a_{31})`);add('Sumar las contribuciones','Suma los tres resultados ya con su signo. Un determinante no nulo indica invertibilidad.',raw`\det A=${t(positive)}+(${t(middle)})+(${t(last)})=${t(detValue!)}`);}
   add('Obtener la transpuesta','Convertimos la primera fila en la primera columna, la segunda fila en la segunda columna, y así sucesivamente. No se invierte el orden de los elementos.',raw`A^T=${matrixTex(a[0].map((_,j)=>a.map(row=>row[j])))}`);
   if(r.details.some(d=>d.label==='Inversa'&&!d.value.startsWith('Singular'))){add('Preparar el cálculo de la inversa','Colocamos la identidad a la derecha. Las operaciones que conviertan A en I convertirán la identidad original en A⁻¹.',raw`[A\mid I]\longrightarrow[I\mid A^{-1}]`);const rows=rowReduction(a,a.map((_,i)=>a.map((_,j)=>i===j?1:0)),steps);add('Leer y comprobar la inversa','Cuando el bloque izquierdo es la identidad, el bloque derecho es la inversa. Compruébala multiplicando A por ese bloque: el resultado debe ser I, salvo redondeo.',raw`A^{-1}=${matrixTex(rows.map(row=>row.slice(size)))}`);}else add('Concluir sobre la inversa','El determinante es cero o demasiado pequeño respecto a la escala de los datos. No presentamos una inversa numérica fiable.');r.latex=raw`\det(A)=${t(detValue!)}`;
  }else{const b=vector(v.vector);add('Escribir el sistema en forma matricial','Cada entrada del vector b es el término independiente de la fila correspondiente. Buscamos el vector de incógnitas que satisface la igualdad.',raw`A\begin{pmatrix}${['x','y','z'].slice(0,size).join(raw`\\`)}\end{pmatrix}=${matrixTex(b.map(x=>[x]))}`);const rows=rowReduction(a,b.map(x=>[x]),steps);r.latex=rows.map((row,i)=>raw`${['x','y','z'][i]}=${t(row[size])}`).join(raw`,\qquad `);add('Leer las incógnitas','La parte izquierda ya es la identidad: cada fila dice directamente cuánto vale una incógnita.',r.latex);for(let i=0;i<size;i++)add(`Comprobar la ecuación ${i+1}`,'Sustituimos todos los valores encontrados en esta fila de la matriz original. El resultado debe coincidir con su término independiente.',raw`${a[i].map((value,j)=>raw`(${t(value)})(${t(rows[j][size])})`).join('+')}\approx${t(b[i])}`);}
 }else if(slug==='inecuaciones'){
  const a=n('a'),b=n('b'),relation=({'<':'<','>':'>','≤':raw`\le`,'≥':raw`\ge`} as Record<string,string>)[v.relation];
  add('Identificar el conjunto que buscamos','Una desigualdad suele tener un intervalo de soluciones, no un único número. Buscamos todos los x que hacen verdadera la comparación.',raw`${t(a)}x+(${t(b)})${relation}0`);
  if(a===0)add('Comprobar el caso sin incógnita','El coeficiente de x es cero. La comparación depende solo de la constante: si es verdadera sirve cualquier real; si es falsa no sirve ninguno.',raw`${t(b)}${relation}0`);
  else{add('Aislar el término con x','Restamos el término independiente en ambos miembros. Sumar o restar la misma cantidad no cambia el sentido de la desigualdad.',raw`${t(a)}x${relation}${t(-b)}`);add('Dividir y decidir el sentido',a<0?'El divisor es negativo. Multiplicar o dividir por un negativo invierte el orden de los números, así que es obligatorio invertir el signo.':'El divisor es positivo. Dividir por él conserva el orden, por lo que el signo no cambia.',raw`x\ ${a<0?({'<':'>','>':'<','\\le':'\\ge','\\ge':'\\le'} as Record<string,string>)[relation]:relation}\ ${t(-b/a)}`);add('Escribir el intervalo','Un signo estricto usa un extremo abierto; ≤ o ≥ incluye el extremo. El infinito siempre se escribe con paréntesis porque no es un número alcanzable.',raw`S=${r.details[0].value.replaceAll('−','-').replaceAll('∞',raw`\infty`)}`);}
  r.latex=r.answer.startsWith('x ')?r.answer.replace('≤',raw`\le`).replace('≥',raw`\ge`):r.answer.startsWith('ℝ')?raw`S=\mathbb R`:raw`S=\varnothing`;
 }else if(slug==='ecuaciones-diferenciales'){
  const node=parse(normalizeExpression(v.expression)),x=n('x0'),y=n('y0'),h=(n('end')-x)/n('steps'),evalAt=(x:number,y:number)=>Number(node.evaluate({x,y}));const k1=evalAt(x,y),k2=evalAt(x+h/2,y+h*k1/2),k3=evalAt(x+h/2,y+h*k2/2),k4=evalAt(x+h,y+h*k3),next=y+h*(k1+2*k2+2*k3+k4)/6;
  add('Identificar la ecuación y la condición inicial','La ecuación nos da una pendiente para cada punto (x,y). La condición inicial fija desde qué punto comienza la trayectoria.',raw`y'=${node.toTex()},\qquad y(${t(x)})=${t(y)}`);
  add('Dividir el intervalo en pasos','Calculamos un avance horizontal constante. Un h negativo permite avanzar hacia valores menores de x.',raw`h=\frac{x_f-x_0}{N}=\frac{${t(n('end'))}-(${t(x)})}{${n('steps')}}=${t(h)}`);
  add('Primera pendiente: inicio del paso','Evaluamos la función en el punto conocido. Esta pendiente sería suficiente para Euler, pero RK4 usa tres evaluaciones adicionales.',raw`k_1=f(x_0,y_0)=f(${t(x)},${t(y)})=${t(k1)}`);
  add('Segunda pendiente: primera estimación del punto medio','Avanzamos medio paso en x y estimamos y usando k₁. Evaluamos de nuevo la pendiente en ese punto provisional.',raw`k_2=f(x_0+h/2,y_0+hk_1/2)=f(${t(x+h/2)},${t(y+h*k1/2)})=${t(k2)}`);
  add('Tercera pendiente: corregir el punto medio','Conservamos el mismo x intermedio, pero mejoramos la estimación de y utilizando k₂.',raw`k_3=f(x_0+h/2,y_0+hk_2/2)=f(${t(x+h/2)},${t(y+h*k2/2)})=${t(k3)}`);
  add('Cuarta pendiente: estimar el final del paso','Avanzamos un paso completo y estimamos y usando k₃. Esta evaluación representa la pendiente al final del intervalo pequeño.',raw`k_4=f(x_0+h,y_0+hk_3)=f(${t(x+h)},${t(y+h*k3)})=${t(k4)}`);
  add('Combinar las cuatro pendientes','Damos peso doble a las dos pendientes del punto medio. La media ponderada se multiplica por h y se suma a y₀.',raw`y_1=y_0+\frac h6(k_1+2k_2+2k_3+k_4)\approx${t(next)}`);
  add('Repetir con el nuevo punto',`Usamos (${f(x+h)}, ${f(next)}) como punto inicial del paso siguiente. Repetimos la misma secuencia hasta completar los ${n('steps')} pasos. La tabla permite seguir la trayectoria completa.`,raw`x_{j+1}=x_j+h,\qquad y_{j+1}=y_j+\frac h6(k_1+2k_2+2k_3+k_4)`);
  r.latex=raw`y(${t(n('end'))})\approx${t(r.plot!.points.at(-1)!.y!)}`;
  add('Interpretar el resultado como aproximación','RK4 no entrega una solución simbólica ni una cota de error automática. Repite el cálculo con el doble de pasos y compara los valores: si cambian mucho, no debes confiar todavía en esa aproximación.',r.latex);
  r.table={headers:['Paso','x','y aproximada'],rows:r.plot!.points.map((p,i)=>[String(i),f(p.x),f(p.y!)])};
 }else{
  // Detailed treatments for the remaining tools are added below.
  steps=explainOther(slug,v,r);
 }
 r.workedSteps=steps;
 if(!r.latex&&/^[-+\d.]+$/.test(r.answer))r.latex=tex(r.answer);
 return r;
}
function explainOther(slug:string,v:Inputs,r:Result):ExplanationStep[]{
 const n=(key:string)=>Number(v[key]),steps:ExplanationStep[]=[];const add=(title:string,explanation:string,latex?:string)=>steps.push(step(title,explanation,latex));
 switch(slug){
 case 'limites':{
  const source=tex(v.expression),a=n('point');r.latex=raw`\lim_{x\to${t(a)}}${source}\quad\text{(exploración numérica)}`;
  add('Distinguir el límite del valor de la función','El límite pregunta qué ocurre cerca del punto, no necesariamente en el punto. Por eso podemos investigar aunque sustituir exactamente produzca una indeterminación.',r.latex);
  add('Elegir distancias pequeñas','Tomamos una distancia h positiva. Para acercarnos por la izquierda usamos a−h y por la derecha a+h.',raw`x_-=(${t(a)})-h,\qquad x_+=(${t(a)})+h`);
  for(const row of r.table!.rows)add(`Acercarse con h = ${row[0]}`,'Evaluamos la misma función en los dos puntos. Compara ambos lados antes de reducir de nuevo la distancia.',raw`f(a-h)=${row[1]==='No definido'?raw`\text{no definido}`:tex(row[1])},\quad f(a+h)=${row[2]==='No definido'?raw`\text{no definido}`:tex(row[2])}`);
  add('Interpretar sin afirmar más de lo observado','Si las columnas parecen acercarse al mismo número, ese número es un candidato. Si divergen o se separan, hay que analizar los límites laterales. Ninguna tabla finita demuestra existencia: puede ocultar oscilaciones o errores de redondeo.');break;
 }
 case 'graficador':{
  r.latex=raw`f(x)=${tex(v.expression)}`;add('Identificar la función y el intervalo','Cada punto de la curva corresponde a una entrada x y a su resultado real f(x). Los ejes muestran esos valores, no una escala decorativa.',r.latex);add('Evaluar puntos del dominio','Elegimos valores de x dentro del intervalo y calculamos f(x). Si la evaluación no es real o no es finita, dejamos un hueco en lugar de inventar un punto.',raw`${t(n('min'))}\le x\le${t(n('max'))}`);add('Relacionar tabla y dibujo','La coordenada horizontal es x y la vertical es f(x). Pasa el cursor sobre la curva para leer pares de valores y usa la tabla para contrastarlos.');add('Explorar con zoom y desplazamiento','Puedes arrastrar la vista o acercarte a una región. En funciones explícitas se vuelve a muestrear el nuevo intervalo para que el dibujo corresponda a los valores que estás explorando.');add('Revisar posibles discontinuidades','El muestreo es finito. Un salto o una asíntota puede quedar entre muestras, por lo que debes comprobar también el dominio algebraico. La gráfica no prueba por sí sola la existencia de una raíz.');break;
 }
 case 'numeros-complejos':{const a=n('a'),b=n('b'),c=n('c'),d=n('d');add('Separar las partes reales e imaginarias','En cada número, el coeficiente de i es la parte imaginaria y el término sin i es la parte real. Recordamos que i² = −1.',raw`z_1=${t(a)}+(${t(b)})i,\quad z_2=${t(c)}+(${t(d)})i,\quad i^2=-1`);
 if(v.operation==='Multiplicar'){add('Distribuir todos los productos','Cada término del primer paréntesis multiplica a cada término del segundo. Conserva i² hasta haber completado la distribución.',raw`z_1z_2=(${t(a)})(${t(c)})+(${t(a)})(${t(d)})i+(${t(b)})(${t(c)})i+(${t(b)})(${t(d)})i^2`);add('Sustituir i² y agrupar','El producto de las partes imaginarias cambia de signo porque i² = −1. Agrupamos los términos reales y los coeficientes de i.',raw`z_1z_2=(${t(a*c)}-${t(b*d)})+(${t(a*d)}+${t(b*c)})i`);r.latex=raw`${t(a*c-b*d)}+(${t(a*d+b*c)})i`;}
 else if(v.operation==='Dividir'){const den=c*c+d*d;add('Multiplicar por el conjugado','Multiplicamos numerador y denominador por c−di. Esta operación equivale a multiplicar por 1 y convierte el denominador en un real.',raw`\frac{a+bi}{c+di}\frac{c-di}{c-di}=\frac{(ac+bd)+(bc-ad)i}{c^2+d^2}`);add('Calcular el denominador','La suma de cuadrados es positiva, salvo que ambos componentes sean cero; ese caso se rechaza antes de calcular.',raw`c^2+d^2=(${t(c)})^2+(${t(d)})^2=${t(den)}`);add('Dividir cada componente','Dividimos tanto la parte real como la parte imaginaria por el mismo denominador.',raw`\frac{${t(a*c+b*d)}}{${t(den)}}+\frac{${t(b*c-a*d)}}{${t(den)}}i`);r.latex=raw`${t((a*c+b*d)/den)}+(${t((b*c-a*d)/den)})i`;}
 else{const sign=v.operation==='Sumar'?1:-1;add('Operar componentes correspondientes','Sumamos o restamos reales con reales e imaginarios con imaginarios. No mezclamos ambos tipos de términos.',raw`(${t(a)}${sign===1?'+':'-'}(${t(c)}))+(${t(b)}${sign===1?'+':'-'}(${t(d)}))i`);r.latex=raw`${t(a+sign*c)}+(${t(b+sign*d)})i`;}
 add('Calcular el módulo','El módulo mide la distancia al origen en el plano complejo. Aplicamos Pitágoras a las dos componentes.',raw`|z_1|=\sqrt{(${t(a)})^2+(${t(b)})^2}=${t(Math.hypot(a,b))}`);add('Presentar el resultado','La respuesta se escribe como parte real más parte imaginaria multiplicada por i.',r.latex);break;}
 case 'potencias-radicales':{const a=n('base'),b=n('exponent');add('Identificar la operación',v.operation==='Raíz'?'Buscamos un número que, elevado al índice indicado, reproduzca el radicando.':'La base es el número sobre el que operamos y el exponente indica la potencia.',v.operation==='Raíz'?raw`\sqrt[${t(b)}]{${t(a)}}`:raw`(${t(a)})^{${t(b)}}`);add('Comprobar el dominio',v.operation==='Raíz'?'El índice es un entero positivo. Si es par, el radicando debe ser no negativo para que exista una raíz real. Si es impar, se admite un radicando negativo.':'Para exponentes no enteros hay que revisar el dominio real. Cero con exponente negativo implica dividir por cero, y aquí 0⁰ se considera indefinido.');add('Calcular respetando el signo','Los paréntesis distinguen elevar una base negativa de tomar el negativo de una potencia. El cálculo conserva esa diferencia.',raw`\text{Resultado}=${tex(r.answer)}`);add('Comprobar la operación inversa',v.operation==='Raíz'?'Eleva el resultado al índice para recuperar el radicando, admitiendo pequeños errores de redondeo.':'Puedes comprobar potencias enteras pequeñas mediante multiplicación repetida o aplicar la raíz correspondiente cuando sea reversible.');break;}
 case 'logaritmos':{const a=n('value'),b=n('base'),out=Number(r.answer);add('Traducir el logaritmo a una pregunta','Preguntamos a qué exponente debemos elevar la base para obtener el argumento.',raw`\log_{${t(b)}}(${t(a)})=x\iff (${t(b)})^x=${t(a)}`);add('Revisar las condiciones','En los reales, el argumento debe ser positivo y la base también; además la base no puede ser 1, porque todas sus potencias serían 1.');add('Usar el cambio de base','Dividimos el logaritmo natural del argumento entre el logaritmo natural de la base. Ambos logaritmos deben usar la misma base.',raw`\log_{${t(b)}}(${t(a)})=\frac{\ln(${t(a)})}{\ln(${t(b)})}`);add('Sustituir los valores numéricos','Calculamos primero los dos logaritmos y después su cociente.',raw`\frac{${t(Math.log(a))}}{${t(Math.log(b))}}=${t(out)}`);add('Comprobar con una potencia','Elevar la base a la respuesta debe devolver aproximadamente el argumento. Es la relación inversa que define el logaritmo.',raw`(${t(b)})^{${t(out)}}\approx${t(a)}`);r.latex=raw`\log_{${t(b)}}(${t(a)})=${t(out)}`;break;}
 case 'sucesiones':{const a=n('first'),d=n('ratio'),count=n('n'),arith=v.type==='Aritmética',last=arith?a+(count-1)*d:a*d**(count-1);add('Identificar la regla de crecimiento',arith?'En una sucesión aritmética sumamos la misma diferencia para pasar al término siguiente.':'En una sucesión geométrica multiplicamos por la misma razón para pasar al término siguiente.',raw`a_1=${t(a)},\quad ${arith?'d':'r'}=${t(d)},\quad n=${count}`);add('Contar los cambios hasta el término n','Del primer término al término n hay n−1 transiciones, no n. Por eso usamos n−1 en la fórmula.',arith?raw`a_n=a_1+(n-1)d`:raw`a_n=a_1r^{n-1}`);add('Calcular el término solicitado','Sustituimos los valores en la fórmula del tipo de sucesión elegido.',arith?raw`a_{${count}}=${t(a)}+(${count}-1)(${t(d)})=${t(last)}`:raw`a_{${count}}=${t(a)}(${t(d)})^{${count}-1}=${t(last)}`);add('Calcular la suma',arith?'Emparejar primer y último término produce la misma suma en cada pareja. Multiplicamos la media de los extremos por la cantidad de términos.':d===1?'Cuando la razón es 1 todos los términos son iguales. La fórmula con 1−r no se usa porque dividiría entre cero.':'Restar r veces la suma a la suma original cancela los términos intermedios y conduce a la fórmula geométrica.',arith?raw`S_n=\frac{n(a_1+a_n)}2=${tex(r.details[0].value)}`:d===1?raw`S_n=na_1=${tex(r.details[0].value)}`:raw`S_n=a_1\frac{1-r^n}{1-r}=${tex(r.details[0].value)}`);r.latex=raw`a_{${count}}=${t(last)},\qquad S_{${count}}=${tex(r.details[0].value)}`;break;}
 case 'trigonometria':{const angle=n('angle'),rad=v.unit==='Grados'?angle*Math.PI/180:angle;add('Identificar la unidad','Una vuelta completa equivale a 360 grados o a 2π radianes. No podemos usar un ángulo en grados como si fuera un valor en radianes.',raw`360^\circ=2\pi\,\text{rad}`);add('Convertir a radianes',v.unit==='Grados'?'Multiplicamos los grados por π/180 antes de evaluar las funciones.':'El ángulo ya está en radianes; no necesitamos convertirlo para evaluarlo.',v.unit==='Grados'?raw`\theta=${t(angle)}\frac{\pi}{180}=${t(rad)}`:raw`\theta=${t(rad)}`);add('Ubicar el punto en la circunferencia unitaria','Coseno es la coordenada horizontal y seno la vertical del punto al recorrer ese ángulo desde el eje positivo x.',raw`(\cos\theta,\sin\theta)=(${t(Math.cos(rad))},${t(Math.sin(rad))})`);add('Calcular la tangente','La tangente es el cociente seno/coseno. Si el coseno es cero, el cociente no está definido; cerca de cero puede ser numéricamente muy inestable.',raw`\tan\theta=\frac{\sin\theta}{\cos\theta}`);add('Comprobar la identidad básica','Los dos valores deben cumplir la identidad pitagórica, salvo redondeo.',raw`\sin^2\theta+\cos^2\theta\approx1`);r.latex=raw`\sin\theta=${t(Math.sin(rad))},\quad\cos\theta=${t(Math.cos(rad))}`;break;}
 case 'triangulos':{const a=n('a'),b=n('b'),c=n('c'),s=(a+b+c)/2,area=Math.sqrt(s*(s-a)*(s-b)*(s-c));add('Verificar que los lados forman un triángulo','Cada lado debe ser positivo y menor que la suma de los otros dos. Si hay igualdad, los puntos quedarían alineados y el triángulo sería degenerado.',raw`a+b>c,\quad a+c>b,\quad b+c>a`);add('Calcular el perímetro y el semiperímetro','Primero sumamos los lados. La fórmula de Herón utiliza la mitad de esa suma.',raw`P=${t(a)}+${t(b)}+${t(c)}=${t(2*s)},\quad s=\frac P2=${t(s)}`);add('Calcular el área con Herón','Multiplicamos el semiperímetro por sus tres diferencias con los lados, y después tomamos la raíz cuadrada.',raw`A=\sqrt{s(s-a)(s-b)(s-c)}=\sqrt{(${t(s)})(${t(s-a)})(${t(s-b)})(${t(s-c)})}=${t(area)}`);for(const [label,u,w,z] of [['A',a,b,c],['B',b,a,c],['C',c,a,b]] as const)add(`Hallar el ángulo ${label}`,'La ley de cosenos relaciona el lado opuesto con los otros dos. Aplicamos arccos y convertimos el resultado a grados.',raw`\cos ${label}=\frac{${t(w)}^2+${t(z)}^2-${t(u)}^2}{2(${t(w)})(${t(z)})}`);add('Comprobar los ángulos','En geometría euclídea los ángulos interiores de un triángulo suman 180°. Esa suma permite revisar el resultado numérico.',raw`A+B+C=180^\circ`);r.latex=raw`\text{Área}=${t(area)}`;break;}
 case 'geometria':{const radius=n('radius'),h=n('height'),base=Math.PI*radius**2;add('Elegir la figura y las unidades',`La figura seleccionada es ${v.shape.toLowerCase()}. Usa una misma unidad para todas las longitudes; al multiplicarlas, el área queda al cuadrado y el volumen al cubo.`,raw`r=${t(radius)}`);add('Calcular la sección circular','La superficie del círculo depende del radio al cuadrado. No confundas radio con diámetro: el diámetro es dos veces el radio.',raw`A_b=\pi r^2=\pi(${t(radius)})^2=${t(base)}`);
 if(v.shape==='Círculo')add('Calcular el perímetro','La longitud de la circunferencia es 2π veces el radio. Es una longitud, no un área.',raw`P=2\pi(${t(radius)})=${t(2*Math.PI*radius)}`);
 else if(v.shape==='Esfera'){add('Calcular el volumen de la esfera','La fórmula usa el cubo del radio; el factor 4/3 relaciona ese cubo con la geometría de la esfera.',raw`V=\frac43\pi(${t(radius)})^3=${t(4*Math.PI*radius**3/3)}`);add('Calcular la superficie de la esfera','Su superficie es cuatro veces el área del círculo de igual radio.',raw`A=4\pi r^2=${t(4*base)}`);}
 else{const cone=v.shape==='Cono';add('Obtener el volumen',cone?'Un cono ocupa un tercio del cilindro con la misma base y altura. Multiplicamos el área de la base por la altura y dividimos entre 3.':'En el cilindro, todas las secciones paralelas a la base tienen la misma área. Multiplicamos esa área por la altura.',cone?raw`V=\frac{A_bh}{3}=\frac{(${t(base)})(${t(h)})}{3}=${t(base*h/3)}`:raw`V=A_bh=(${t(base)})(${t(h)})=${t(base*h)}`);add('Sumar la superficie lateral y las bases',cone?'La generatriz g se calcula por Pitágoras. La superficie total suma el área lateral πrg y una base circular.':'El área lateral equivale a un rectángulo de base 2πr y altura h. Añadimos las dos bases circulares.',cone?raw`g=\sqrt{r^2+h^2}=${t(Math.hypot(radius,h))},\quad A_T=\pi r(r+g)`:raw`A_T=2\pi rh+2\pi r^2`);}
 add('Comprobar las unidades y la escala','El perímetro se expresa en unidades de longitud, el área en unidades cuadradas y el volumen en unidades cúbicas. Si duplicas todas las longitudes, las áreas se multiplican por cuatro y los volúmenes por ocho.');
 r.latex=raw`\text{${r.answer.split('=')[0].trim()}}=${tex(r.answer.split('=')[1].trim())}`;break;}
 case 'vectores':{const u=vector(v.u),w=vector(v.v),dot=u.reduce((s,x,i)=>s+x*w[i],0),nu=Math.hypot(...u),nw=Math.hypot(...w);add('Alinear las componentes','Ambos vectores deben tener la misma dimensión. La primera componente de uno corresponde a la primera del otro, y así sucesivamente.',raw`u=${matrixTex(u.map(x=>[x]))},\quad v=${matrixTex(w.map(x=>[x]))}`);add('Sumar componente a componente','La suma de vectores produce otro vector: cada coordenada es la suma de las coordenadas correspondientes.',raw`u+v=${matrixTex(u.map((x,i)=>[x+w[i]]))}`);add('Calcular el producto escalar','Multiplicamos las componentes correspondientes y sumamos esos productos. El resultado es un escalar, no un vector.',raw`u\cdot v=${u.map((x,i)=>raw`(${t(x)})(${t(w[i])})`).join('+')}=${t(dot)}`);add('Calcular las longitudes','La norma se obtiene con Pitágoras en dos o tres dimensiones.',raw`\|u\|=\sqrt{${u.map(x=>raw`(${t(x)})^2`).join('+')}}=${t(nu)},\quad\|v\|=${t(nw)}`);add('Relacionar producto y ángulo',nu&&nw?'Despejamos el coseno del ángulo y aplicamos arccos. El ángulo resultante se convierte a grados.':'Uno de los vectores es cero: no tiene una dirección definida y no puede asignarse un ángulo con el otro.',nu&&nw?raw`\cos\theta=\frac{u\cdot v}{\|u\|\|v\|}=\frac{${t(dot)}}{(${t(nu)})(${t(nw)})}`:undefined);if(u.length===3)add('Calcular el producto vectorial','En tres dimensiones, el producto vectorial tiene tres componentes obtenidas de menores con signos alternados. El vector resultante es perpendicular a los dos originales.',raw`u\times v=(u_2v_3-u_3v_2,\ u_3v_1-u_1v_3,\ u_1v_2-u_2v_1)`);r.latex=raw`u\cdot v=${t(dot)}`;break;}
 case 'geometria-analitica':{const a=n('x1'),b=n('y1'),c=n('x2'),d=n('y2');add('Calcular los desplazamientos','Restamos las coordenadas del primer punto a las del segundo. Estas diferencias describen los catetos de un triángulo rectángulo auxiliar.',raw`\Delta x=${t(c)}-(${t(a)})=${t(c-a)},\quad\Delta y=${t(d)}-(${t(b)})=${t(d-b)}`);add('Aplicar Pitágoras para la distancia','La distancia es siempre no negativa. Al elevar al cuadrado, el sentido de los desplazamientos no cambia la longitud.',raw`d=\sqrt{(\Delta x)^2+(\Delta y)^2}=${t(Math.hypot(c-a,d-b))}`);add('Promediar para hallar el punto medio','Calculamos por separado el promedio de las coordenadas horizontales y el de las verticales.',raw`M=\left(\frac{${t(a)}+(${t(c)})}{2},\frac{${t(b)}+(${t(d)})}{2}\right)=(${t((a+c)/2)},${t((b+d)/2)})`);if(a!==c){const m=(d-b)/(c-a);add('Calcular la pendiente','La pendiente es el cambio vertical dividido entre el horizontal. Aquí el cambio horizontal no es cero.',raw`m=\frac{\Delta y}{\Delta x}=${t(m)}`);add('Escribir la ecuación de la recta','Usamos un punto conocido y la pendiente. Desarrollar la forma punto-pendiente permite identificar el intercepto.',raw`y-(${t(b)})=(${t(m)})(x-(${t(a)}))\iff y=(${t(m)})x+(${t(b-m*a)})`);}else add('Tratar el caso vertical',b===d?'Los dos puntos son idénticos y no determinan una recta única.':'El cambio horizontal es cero. La recta es vertical y se escribe x igual a la coordenada común; su pendiente no es finita.',b!==d?raw`x=${t(a)}`:undefined);r.latex=raw`d=${t(Math.hypot(c-a,d-b))}`;break;}
 case 'conjuntos':{const clean=(s:string)=>[...new Set(s.split(',').map(x=>x.trim()).filter(Boolean))],a=clean(v.a),b=clean(v.b);add('Eliminar duplicados','Un conjunto representa pertenencia, no frecuencia. Quitamos elementos repetidos y espacios exteriores. Aquí comparamos las etiquetas exactamente, distinguiendo mayúsculas.');add('Construir la unión','Recorremos ambos conjuntos y guardamos cada etiqueta una vez. Un elemento pertenece a A∪B si pertenece al menos a uno de ellos.',raw`x\in A\cup B\iff(x\in A)\lor(x\in B)`);add('Construir la intersección','Recorremos los elementos de A y conservamos solo los que también aparecen en B.',raw`x\in A\cap B\iff(x\in A)\land(x\in B)`);add('Calcular las diferencias','Para A∖B eliminamos de A los elementos que están en B. Para B∖A hacemos el proceso contrario; estas operaciones no son, en general, iguales.',raw`A\setminus B=\{x:x\in A\land x\notin B\}`);add('Obtener la diferencia simétrica','Reunimos los elementos exclusivos de A y los exclusivos de B; los comunes quedan fuera.',raw`A\triangle B=(A\setminus B)\cup(B\setminus A)`);add('Contar pares del producto cartesiano','Cada elemento de A se combina con cada elemento de B. Multiplicar las cantidades cuenta todos los pares ordenados.',raw`|A\times B|=|A|\,|B|=${a.length}\cdot${b.length}=${a.length*b.length}`);break;}
 case 'combinatoria':{const a=n('n'),b=n('r');add('Decidir si importa el orden','Elegir integrantes de un grupo y asignarles cargos son problemas distintos. La calculadora muestra ambos: combinaciones sin orden y variaciones con orden. No hay repetición.');add('Contar elecciones ordenadas','Para el primer lugar hay n opciones; para el segundo, n−1, y así hasta elegir r elementos. El producto se escribe con factoriales.',raw`V(n,r)=\frac{n!}{(n-r)!}=\frac{${a}!}{${a-b}!}=${r.details[0].value}`);add('Eliminar los órdenes repetidos','Cada grupo de r elementos fue contado r! veces, una por cada orden posible. Dividimos entre r! para que cada grupo se cuente una sola vez.',raw`C(n,r)=\frac{V(n,r)}{r!}=\frac{${a}!}{${b}!\,${a-b}!}`);add('Presentar el número de grupos','El resultado es un entero exacto calculado con aritmética de enteros grandes.',raw`C(${a},${b})=${r.answer.split('=')[1].trim()}`);add('Contar las permutaciones completas','Si ordenamos todos los elementos, r=n. Hay n opciones para el primer puesto, n−1 para el segundo y así hasta llegar a 1.',raw`P(n)=n!=${r.details[1].value}`);r.latex=raw`\binom{${a}}{${b}}=${r.answer.split('=')[1].trim()}`;break;}
 case 'teoria-numeros':{let a=n('a'),b=n('b');add('Aplicar la idea de Euclides','El máximo común divisor no cambia al sustituir la pareja (a,b) por (b, resto de a entre b). Repetimos hasta que el resto sea cero.',raw`\gcd(a,b)=\gcd(b,a\bmod b)`);let i=1;while(b){const rest=a%b;add(`División euclídea ${i++}`,`Dividimos ${a} entre ${b}: el cociente es ${Math.floor(a/b)} y el resto ${rest}. La siguiente pareja usa el divisor y ese resto.`,raw`${a}=${Math.floor(a/b)}\cdot${b}+${rest}`);a=b;b=rest;}add('Identificar el último resto no nulo','Cuando el siguiente resto es cero, el último divisor es el máximo común divisor.',raw`\gcd(${n('a')},${n('b')})=${a}`);add('Calcular el mínimo común múltiplo','El producto de dos enteros positivos es igual al producto de su mcd y su mcm. Despejamos el mcm dividiendo primero para reducir el tamaño de los números.',raw`\operatorname{mcm}(a,b)=\frac{ab}{\gcd(a,b)}=${r.details[0].value}`);add('Leer la factorización prima','Se prueban divisores desde 2 y se divide repetidamente mientras el resto sea cero. El número de divisiones por un primo es su exponente en la factorización.');r.latex=raw`\gcd(${n('a')},${n('b')})=${a}`;break;}
 case 'probabilidad':{const count=n('n'),k=n('k'),p=n('p');add('Comprobar el modelo binomial','Cada ensayo tiene dos resultados, los ensayos son independientes y la probabilidad de éxito p se mantiene constante. Sin esas condiciones, esta fórmula puede no describir el problema.',raw`X\sim\operatorname{Bin}(${count},${t(p)})`);add('Contar las posiciones de los éxitos','Elegimos en qué k ensayos ocurren los éxitos. El orden de esa elección no importa, de ahí el coeficiente binomial.',raw`\binom nk=\frac{n!}{k!(n-k)!}`);add('Calcular una secuencia concreta','Una secuencia con k éxitos y n−k fracasos tiene esta probabilidad porque multiplicamos probabilidades de sucesos independientes.',raw`p^k(1-p)^{n-k}=(${t(p)})^{${k}}(1-${t(p)})^{${count-k}}`);add('Reunir las secuencias posibles','Multiplicamos la probabilidad de cada secuencia por la cantidad de posiciones posibles de los éxitos.',raw`P(X=${k})=\binom{${count}}{${k}}(${t(p)})^{${k}}(1-${t(p)})^{${count-k}}=${r.answer.split('= ').at(-1)}`);add('Obtener la probabilidad acumulada','«Como máximo k» incluye cero éxitos, uno, dos y todos los valores hasta k. Sumamos esas probabilidades, no solo la del último valor.',raw`P(X\le${k})=\sum_{j=0}^{${k}}\binom{${count}}j p^j(1-p)^{${count}-j}=${r.details[0].value}`);add('Interpretar media y varianza','La media es el número esperado de éxitos en muchas repeticiones del experimento; no tiene que ser entero. La varianza describe la dispersión.',raw`E[X]=np=${t(count*p)},\qquad\operatorname{Var}(X)=np(1-p)=${t(count*p*(1-p))}`);r.latex=raw`P(X=${k})=${r.answer.split('= ').at(-1)}`;break;}
 case 'estadistica':{const data=vector(v.data),sorted=[...data].sort((a,b)=>a-b),count=data.length,sum=data.reduce((s,x)=>s+x,0),mean=sum/count,squared=data.reduce((s,x)=>s+(x-mean)**2,0),den=v.type==='Muestral'?count-1:count;add('Contar y ordenar los datos','Contamos cada observación, incluidas las repetidas. Ordenar no altera la media, pero es necesario para localizar la mediana.',raw`n=${count}`);add('Calcular la media','Sumamos todos los valores y dividimos entre el número de observaciones. Todos los datos tienen el mismo peso.',raw`\bar x=\frac{\sum x_i}{n}=\frac{${t(sum)}}{${count}}=${t(mean)}`);add('Localizar la mediana',count%2?'Con una cantidad impar, tomamos el dato de la posición central de la lista ordenada.':'Con una cantidad par, promediamos las dos observaciones centrales de la lista ordenada.',raw`\operatorname{Mediana}=${tex(r.details[0].value)}`);add('Medir las desviaciones respecto a la media','Para cada observación restamos la media y elevamos al cuadrado. Los cuadrados impiden que desviaciones positivas y negativas se cancelen.',raw`\sum_{i=1}^{n}(x_i-\bar x)^2=${t(squared)}`);r.table={headers:['Dato','Desviación','Desviación²'],rows:data.map(x=>[f(x),f(x-mean),f((x-mean)**2)])};add('Elegir el denominador correcto',v.type==='Muestral'?'Usamos n−1 porque estimamos una varianza poblacional a partir de una muestra. Al estimar previamente la media perdemos un grado de libertad.':'Usamos n porque tratamos los datos introducidos como la población completa que estamos describiendo.',raw`${v.type==='Muestral'?'s^2':raw`\sigma^2`}=\frac{${t(squared)}}{${den}}=${t(squared/den)}`);add('Volver a las unidades de los datos','La varianza está en unidades al cuadrado. Su raíz cuadrada, la desviación estándar, vuelve a la unidad original y facilita interpretar la dispersión.',raw`${v.type==='Muestral'?'s':raw`\sigma`}=\sqrt{${t(squared/den)}}=${t(Math.sqrt(squared/den))}`);add('Revisar los extremos','El mínimo y máximo muestran el intervalo observado. Una media por sí sola puede ocultar asimetrías o valores atípicos.',raw`x_{\min}=${t(sorted[0])},\qquad x_{\max}=${t(sorted.at(-1)!)}`);r.latex=raw`\bar x=${t(mean)}`;break;}
 case 'regresion-lineal':{const x=vector(v.x),y=vector(v.y),count=x.length,mx=x.reduce((s,v)=>s+v,0)/count,my=y.reduce((s,v)=>s+v,0)/count,sxx=x.reduce((s,v)=>s+(v-mx)**2,0),sxy=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0),m=sxy/sxx,b=my-m*mx;add('Emparejar los datos','Cada x debe estar asociado con el y de la misma posición. Buscamos una recta que minimice la suma de los errores verticales al cuadrado.',raw`\hat y=mx+b`);add('Calcular las medias','Las medias ubican el centro de la nube de puntos. La recta de mínimos cuadrados con intercepto pasa por ese centro.',raw`\bar x=${t(mx)},\qquad\bar y=${t(my)}`);add('Calcular la variación de x y la covariación','Centramos cada dato restando su media. Sumamos cuadrados de las desviaciones de x y productos de las desviaciones de x e y.',raw`S_{xx}=\sum(x_i-\bar x)^2=${t(sxx)},\quad S_{xy}=\sum(x_i-\bar x)(y_i-\bar y)=${t(sxy)}`);add('Obtener la pendiente','Dividimos la covariación entre la variación de x. Esto expresa cuánto cambia la predicción de y por cada unidad adicional de x.',raw`m=\frac{S_{xy}}{S_{xx}}=\frac{${t(sxy)}}{${t(sxx)}}=${t(m)}`);add('Obtener el intercepto','La recta pasa por el centro de los datos. Sustituimos las medias en y = mx + b y despejamos b.',raw`b=\bar y-m\bar x=${t(my)}-(${t(m)})(${t(mx)})=${t(b)}`);r.latex=raw`\hat y=(${t(m)})x+(${t(b)})`;add('Escribir la recta y calcular residuos','Para cada entrada calculamos una predicción y la restamos al valor observado. Un residuo positivo indica que el dato está por encima de la recta.',r.latex);r.table={headers:['x','y observada','ŷ estimada','Residuo'],rows:x.map((value,i)=>[f(value),f(y[i]),f(m*value+b),f(y[i]-m*value-b)])};add('Interpretar R² con cautela','R² compara el error residual con la variación total de y. Si y es constante, el denominador es cero y R² no se define aquí. Un buen ajuste no demuestra causalidad ni garantiza predicciones fuera del intervalo.',raw`R^2=1-\frac{\sum(y_i-\hat y_i)^2}{\sum(y_i-\bar y)^2}`);break;}
 }
 return steps.length?steps:r.steps.map((s,i)=>step(`Paso ${i+1}`,s));
}
